config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'posts#index'

  resources :posts
  post '/', to: 'posts#create'

  resources :users do
    resources :friendships, only: %i[new create destroy index update] do
      post 'accept', to: 'friendships#update'
      delete 'decline', to: 'friendships#destroy'
    end
  end

  resources :comments, only: %i[new create show]
  resources :likes, only: %i[new create show]

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
    get 'login', to: 'devise/sessions#new'
  end

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/friendship.rb
# frozen_string_literal: true

class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
  validates_uniqueness_of :user_id, scope: :friend_id
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :user_id, scope: :post_id
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments
  validates :content, presence: true
  scope :right_order, -> { order(created_at: :desc) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :friendships
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: :friend

  include Gravtastic
  gravtastic
  is_gravtastic

  def friends
    friendships.map { |friendship| friendship.friend if friendship.accepted }
  end

  # Users who have yet to confirme friend requests
  def pending_friends
    friendships.map { |friendship| friendship.friend unless friendship.accepted }.compact
  end

  # Users who have requested to be friends
  def friend_requests
    inverse_friendships.map { |friendship| friendship.user unless friendship.accepted }.compact
  end

  def friend?(user)
    friends.include?(user)
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.password = Devise.friendly_token[0,20]

      user.username = auth.info.name
    end
  end

  def find_friendship(friend)
    Friendship.where('user_id = ? and friend_id = ?', id, friend.id).take ||
      Friendship.where('user_id = ? and friend_id = ?', friend.id, id).take
  end

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    redirect_back(fallback_location: root_path) if @comment.save
  end

  def show
    @comments = @post.comments
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/friendships_controller.rb
# frozen_string_literal: true

class FriendshipsController < ApplicationController
  def new
    @friendship = Friendship.new
  end

  def create
    @friendship = Friendship.new(friendship_params)
    if @friendship.save
      flash[:success] = 'Friendship successfully sent'
    else
      flash[:danger] = 'Friendship not sent'
    end
    redirect_back(fallback_location: root_path)
  end

  def update
    @friendship = Friendship.find(params[:friendship_id])
    @friendship.accepted = true
    if save_double_user
      flash[:success] = 'Friendship accepted'
    else
      flash[:danger] = 'Try again'
    end
    redirect_back(fallback_location: root_path)
  end

  def index
    @friend_requests = current_user.friend_requests
    @pending_requests = current_user.pending_friends
  end

  def destroy
    friendship = Friendship.find(params[:id])
    inverse_friendship = current_user.find_friendship(friendship.user)
    if friendship.delete
      inverse_friendship&.delete
      flash[:success] = 'Friendship deleted'
    else
      flash[:danger] = 'Try again'
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def friendship_params
    params.require(:friendship).permit(:user_id, :friend_id)
  end

  def save_double_user
    ActiveRecord::Base.transaction do
      @friendship.save
      Friendship.create(user: @friendship.friend, friend: @friendship.user, accepted: true)
    end
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

# before_action :find_like, only: [:destroy]

class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @like = Like.new(like_params)
    @like.user = current_user
    redirect_back(fallback_location: root_path) if @like.save
  end

  private

  def like_params
    params.require(:like).permit(:post_id)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.build(post_params)

    if @post.save
      flash[:success] = 'Post created'
      redirect_back(fallback_location: root_path)
    else
      flash.now[:danger] = 'Try again'
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.new
    @user = @post.user
  end

  def index
    @post = Post.new
    @posts = Post.all.right_order
    @comments = @post.comments
    @comment = @post.comments.new
    @likes = @post.likes
    @like = @post.likes.new
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, except: %i[new create]

  def new; end

  def create; end

  def show
    @user = User.find(params[:id])
    @comment = Comment.new
    @post = Post.new
    @like = Like.new
  end

  def index
    @users = User.all
    @friendship = Friendship.new
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/friendships_helper.rb
# frozen_string_literal: true

module FriendshipsHelper
  def pending?(user)
    pending_friends = current_user.pending_friends
    pending_friends.include?(user)
  end
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/comments/_comment.html.erb
<h3 class="pl-4">Comments</h3>
<ul class="comments-list pb-3 px-0"> 
  <% object.each do |c|%> 
    <li  class= "row col-12 pb-1">
      <div class="pr-1">
        <%= image_tag c.user.gravatar_url(size:20), class:"rounded-circle"%>
      </div>
      <div class="comment-content row col-10">
        <p class="pl-1 mb-0"> 
          <span class="user-comment mb-0 pl-1"><%= link_to c.user.username %> </span>
          <%= c.content %> 
        </p>
      </div>
    </li>
  <% end %>
</ul>

app/views/comments/_create.html.erb
<%= form_with model: @comment, class:"row" do |f| %>
  <div class="comment-field col-12 m-auto">
    <%= f.text_field :content, id:"submit-comment", class: 'col-12 py-3 border-0', placeholder: 'Post a comment...'  %>
    <%= f.hidden_field :post_id, value: post_id%>
  </div>
  <!-- <div class="actions text-right col-2">
    <%= f.submit "Comment", class:"btn submit w-25 mb-0" %>
  </div> -->
<% end %>

app/views/comments/new.html.erb
<%= render 'create' %>

app/views/friendships/_pending.html.erb
<h2 class="text-center my-5">Pending requests</h2>
<ul class="users-list col-8 m-auto">
    <% if @pending_requests.empty? %>
        <div class="card">
        <p class = "text-center font-weight-bold red">All your requests have been accepted</p>
        </div>    
    <% else %>
        <% @pending_requests.each do |user | %>
        <li class='user-info col-12 card'>
            <div class="row col-9 mx-auto my-5 d-flex justify-content-center">
                <div class='col-7 row'>
                    <div class="col-5"> <%= image_tag user.gravatar_url %> </div>
                    <p class="col-7"><%= link_to user.username, user_path(user.id) %></p>
                </div>
            </div>
        </li>
        <% end %>
    <% end %>
</ul>

app/views/friendships/_requested.html.erb
<h2 class="text-center my-5">Friendship requests</h2>
<ul class="users-list col-8 m-auto">
    <% if @friend_requests.empty? %>
        <div class="card">
        <p class = "text-center font-weight-bold red">There are no friend requests</p>
        </div>    
    <% else %>
        <% @friend_requests.each do |user| %>
        <li class='user-info col-12 card'>
            <div class="row col-9 mx-auto my-5 d-flex justify-content-center">
                <div class='col-7 row'>
                    <div class="col-5"> <%= image_tag user.gravatar_url %> </div>
                    <p class="col-7"><%= link_to user.username, user_path(user.id) %></p>
                </div>
                <div class="col-5 row d-flex justify-content-between">
                    <%= button_to 'Accept', user_friendship_accept_path(friendship_id: user.find_friendship(current_user)), class:"btn btn-success" %>
                    <%= button_to 'Decline', user_friendship_path(id: user.find_friendship(current_user)), method: :delete, class:"btn btn-danger" %>
                </div>
            </div>
        </li>
        <% end %>
    <% end %>
</ul>

app/views/friendships/index.html.erb
<%= render 'requested' %>
<%= render 'pending' %>

app/views/layouts/_header.html.erb
<nav id='logo' class="navbar navbar-expand-md mb-5 w-100">
    <p class="navbar-brand m-0">SocialBook</p>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"><%= image_tag 'menu-icon', class: "w-75" %></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="collapse navbar-collapse list-style-none justify-content-end align-items-center m-0" id="navbarSupportedContent">
            <% if user_signed_in? %>
                <li class="nav-item"><%= link_to "Home", root_path, class:"nav-link" %></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= current_user.username%>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <%= link_to 'Profile', user_path(current_user), class:"dropdown-item" %>
                        <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
                    </div>
                </li>
                <li class="nav-item"><%= link_to "Notifications", user_friendships_path(current_user), class:"nav-link" %>
                    <% if !current_user.friend_requests.empty? %>
                    <span class="badge badge-danger"><%= current_user.friend_requests.count %></span>
                    <% end %>
                </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/f6db959ed1.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <header class="p-0">
    <%= render 'layouts/header' %>
  </header>

  <% unless controller_name == 'sessions' || controller_name == 'registrations' || controller_name == 'passwords'%>
    <body class = 'container-fluid bg-app p-0'>
      <% flash.each do |name, message| %>
        <div class="alert alert-<%= name %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </body>
  <% else %>
     <body class = 'container-fluid bg-login p-0'>
      <% flash.each do |name, message| %>
        <div class="alert alert-<%= name %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </body>
  <% end %>
</html>

app/views/layouts/home.html.erb
<div class = 'bg-login'>
  <%= render 'new_user_session_path' %>
</div>

app/views/likes/_likes.html.erb
<%= form_with model: @like do |f| %>
    <%= f.hidden_field :post_id, value: post_id%>
    <%= f.submit "", class:'btn-like'%>
<% end %>

app/views/likes/new.html.erb
<%= render 'likes' %>

app/views/posts/_create.html.erb
<div class="col-6 mx-auto mb-5 bg-white post p-3">
  <%= form_with model: @post do |f| %>
    <div class="">
      <%= f.text_area :content, placeholder: "Post something...", class: 'col-12 text-area'  %>
    </div>
    <div class="actions text-right">
      <%= f.submit "Post", class:"btn submit w-25" %>
    </div>
  <% end %>
</div>

app/views/posts/_posts.html.erb
<ul class="posts-list col-6 m-auto p-0">
  <% object.each do |post|%>
    <% if current_user.friends.include?(post.user) || post.user == current_user%>  
      <li class='col-12 post mb-5 py-4 px-0'>
        <div class="row col-12 post-name border-bottom mb-1 pb-3 m-auto px-5">
          <%= image_tag post.user.gravatar_url(size:40), class:"rounded-circle"%>
          <div class="d-flex flex-column text-left pl-2">
            <p class="font-weight-bold m-0"><%= post.user.username %></p>
            <p class="text-secondary m-0">Posted <%= time_ago_in_words(post.created_at)%> ago</p>
          </div>
        </div>
        <p class="col-12 border-bottom mb-1 py-5"> <%= post.content %> </p>
        <div class="post-footer col-12 d-flex justify-content-start px-5 py-2">
          <div class='like d-flex align-items-center py-0 pr-2'>
            <%= render 'likes/likes', post_id: post.id, post: post %>
            <p class='m-0 pl-1 text-secondary'><%= pluralize(post.likes.count, 'Like') %></p>
          </div>
          <div class='comment d-flex align-items-center p-0'>
            <button class="btn-comment" type="button" data-toggle="collapse" data-target="#comments-toggle" aria-expanded="false" aria-controls="comments-toggle"></button>
            <p class='m-0 pl-1 text-secondary'><%= pluralize(post.comments.count, 'Comment') %></p>
          </div>
        </div>
        <div id="comments-toggle" class="collapse border-bottom">
          <div class='comment-list col-12 text-left pl-5 pt-3'>
            <%= render 'comments/comment', object: post.comments %>
          </div>
        </div>
        <div class="create-comment col-10 mx-auto mt-3">
          <%= render 'comments/create', post_id: post.id %>
        </div>
      </li>
      <% end %>
  <% end %>
</ul>

app/views/posts/index.html.erb
<h1 class='mx-auto text-center mb-5'>Newsfeed</h1>
<div class="col-10 m-auto">
  <%= render 'create' %>
  <%= render 'posts', object: @posts %>
</div>

app/views/posts/new.html.erb
<%= render 'create' %>

app/views/posts/show.html.erb
<div class= 'card row'>
  <div class= "row col-8">
    <%= image_tag @post.user.gravatar_url(size:40)%>
    <p class = "font-weight-bold col-8"><%= @post.user.username %></p>
  </div>
  <body class= "col-8"> <%= @post.content %> </body>
  <p>Posted <%= time_ago_in_words(@post.created_at)%> ago</p>
  <div class='col-12'>
    <%= render 'comments/comment', object: @post.comments %>
  </div>
  <div class='col-12'>
    <%= render 'comments/create' %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li class="error_msg"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_login.html.erb
<div class="col-7 row mx-auto my-5 pt-5">
  <div class="col-7 p-5 bg-purp rounded-left d-flex flex-column justify-content-between">
  <div class='row d-flex justify-content-center col-8 mx-auto'>
    <%= image_tag 'logo', class: 'col-12 logo align-self-center'%>
    <h2 class="text-white text-center mb-3 col-12">Welcome to your app</h2>
  </div>
  <p class="text-white text-center mb-5">Sign in to access the system</p>
  <p class="text-white text-center">www.yourapp.com</p>
</div>

app/views/users/_user.html.erb
    <div class=col-2>
        <%= image_tag @user.gravatar_url %>
    </div>
    <div class='col-3'>
        <%= @user.username %>
        <br>
        <%= @user.email %>
    </div>

app/views/users/index.html.erb
<h2 class="text-center my-5">Users</h2>
<ul class="users-list">
    <% @users.each do |user| %>
        <% if  current_user != user %>  
            <li class='user-info col-12'>
                <div class="row col-9 mx-auto my-5 d-flex justify-content-center">
                    <div class='col-6 row'>
                        <div class="col-5"> <%= image_tag user.gravatar_url %> </div>
                        <p class="col-7"><%= link_to user.username, user_path(user.id) %></p>
                    </div>
                    <div class='friendship-button'>
                        <% if !current_user.friend?(user) && !current_user.pending_friends.include?(user)%>
                            <%= button_to 'Add friend', user_friendships_path(current_user, friendship: { user_id: current_user, friend_id: user.id }), method: :post, class:"btn btn-primary add-friend" %>
                        <% elsif current_user.friend?(user) %>
                            <%= button_to 'Delete friend', user_friendship_path(current_user, id: user.find_friendship(current_user)), method: :delete, class:"btn btn-danger delete-friend" %>
                        <% elsif current_user.pending_friends.include?(user) %>
                            <%= link_to 'Friend added', user, class:"btn btn-secondary" %>
                        <% end %>
                    </div>
                </div>
            </li>
        <% end %>   
    <% end %>
</ul>

app/views/users/show.html.erb
<div class='row col-8 mx-auto d-flex justify-content-center my-5'>
  <%= render 'user' %>
</div>
<%= render 'posts/posts', object: @user.posts %>